---
- name: "cockpit: Load variables"
  include_vars:
    file: "cockpit.yml"

- name: "cockpit: Ensure state of repository"
  when: cockpit_repos|length > 0
  become: true
  yum_repository:
    name: "{{ cockpit_repo.name }}"
    baseurl: "{{ cockpit_repo.baseurl }}"
    description: "{{ cockpit_repo.description | default(omit) }}"
    gpgcheck: "{{ cockpit_repo.gpgcheck | default(omit) }}"
    enabled: "{{ cockpit_repo.enabled | default(omit) }}"
    repo_gpgcheck: "{{ cockpit_repo.repo_gpgcheck | default(omit) }}"
    gpgkey: "{{ cockpit_repo.gpgkey | default(omit) }}"
  loop: "{{ cockpit_repos }}"
  loop_control:
    loop_var: cockpit_repo
  tags:
    - configure

- name: "cockpit: Ensure state of packages"
  when: cockpit_packages|length > 0
  become: true
  yum:
    name: "{{ cockpit_package.name }}"
    state: "{{ cockpit_package.state | default(omit) }}"
    update_cache: "{{ cockpit_package.update_cache | default(omit) }}"
  loop: "{{ cockpit_packages }}"
  loop_control:
    loop_var: cockpit_package
  tags:
    - install

- name: "cockpit: Ensure service state"
  become: true
  service:
    name: "{{ cockpit_service.name }}"
    state: "{{ cockpit_service.state }}"
    enabled: "{{ cockpit_service.enabled }}"
  tags:
    - config
