---
- name: "libvirt: Load variables"
  include_vars:
    file: "libvirt.yml"

- name: "libvirt: Ensure state of packages"
  become: true
  yum:
    name: "{{ libvirt_package.name }}"
    state: "{{ libvirt_package.state }}"
    update_cache: "{{ libvirt_package.update_cache }}"
  loop: "{{ libvirt_packages | default([]) }}"
  loop_control:
    loop_var: libvirt_package
  tags:
    - install

- name: "libvirt: Ensure state of image files"
  become: true
  copy:
    src: "{{ libvirt_images_path.local }}"
    dest: "{{ libvirt_images_path.remote }}"
    owner: "{{ libvirt_images_path.owner }}"
    group: "{{ libvirt_images_path.group }}"
    force: yes
  tags:
    - install

- name: "libvirt: Ensure state of permissions in images folder"
  become: true
  file:
    path: "{{ libvirt_images_path.remote }}"
    owner: "{{ libvirt_images_path.owner }}"
    group: "{{ libvirt_images_path.owner }}"
    recurse: yes
    state: directory
  tags:
    - config

- name: "libvirt: Ensure service state"
  service:
    name: "{{ libvirt_service.name }}"
    state: "{{ libvirt_service.state }}"
    enabled: "{{ libvirt_service.enabled }}"
  tags:
    - config

- name: "libvirt: Ensure Polkit Localauthority"
  become: true
  template:
    src: "{{ libvirt_auth.src }}"
    dest: "{{ libvirt_auth.dest }}"
    mode: '0600'
  notify: libvirtd_reload
  tags:
    - config
