---
- name: "setup"
  include_tasks: setup.yml

- name: "user"
  include_tasks: user.yml

- name: "ansible"
  include_tasks: ansible.yml
  when: darkbulb_ansible|bool

- name: "cockpit"
  include_tasks: cockpit.yml
  when: darkbulb_cockpit|bool

- name: "libvirt"
  include_tasks: libvirt.yml
  when: darkbulb_libvirt|bool

- name: "vagrant"
  include_tasks: vagrant.yml
  when: darkbulb_vagrant|bool

- name: "virtualbox"
  include_tasks: virtualbox.yml
  when: darkbulb_virtualbox|bool
