---
- name: "ansible"
  include_tasks: ansible.yml
  when: darkbulb_ansible|bool

- name: "cockpit"
  include_role:
    name: victorock.cockpit
  vars:
    autorun: darkbulb_cockpit|bool

- name: "libvirt"
  include_role:
    name: victorock.libvirt
  vars:
    autorun: darkbulb_libvirt|bool

- name: "gns3_server"
  include_role:
    name: victorock.gns3_server
  vars:
    autorun: darkbulb_gns3_server|bool

- name: "vagrant"
  include_tasks: vagrant.yml
  when: darkbulb_vagrant|bool

- name: "virtualbox"
  include_tasks: virtualbox.yml
  when: darkbulb_virtualbox|bool

- name: "setup"
  include_tasks: setup.yml
