---
- import_tasks: setup.yml
- import_tasks: user.yml

- import_tasks: ansible.yml
  when: darkbulb_ansible|bool

- import_tasks: cockpit.yml
  when: darkbulb_cockpit|bool

- import_tasks: libvirt.yml
  when: darkbulb_libvirt|bool

- import_tasks: vagrant.yml
  when: darkbulb_vagrant|bool

- import_tasks: virtualbox.yml
  when: darkbulb_virtualbox|bool
