---
- name: "setup: Load variables"
  include_vars:
    file: "setup.yml"

- name: "setup: Ensure state of packages"
  when: setup_packages|length > 0
  become: true
  yum:
    name: "{{ setup_package.name | default(setup_package) }}"
    state: "{{ setup_package.state | default(omit) }}"
    update_cache: "{{ setup_package.update_cache | default(omit) }}"
  loop: "{{ setup_packages }}"
  loop_control:
    loop_var: setup_package

- name: "setup: Ensure state of user as member of libvirt"
  become: true
  user:
    name: "{{ ansible_user }}"
    groups: "{{ setup_libvirt_group }}"
    append: yes
