- name: "user: Load variables"
  include_vars:
    file: "user.yml"

- name: "user: Ensure state of user account"
  become: true
  user:
    name: "{{ user_instance.user }}"
    home: "{{ user_instance.homedir }}"
    createhome: yes
    append: yes
  tags:
    - configure

- name: "user: Ensure state of keychain ssh source folder"
  delegate_to: localhost
  run_once: true
  become: false
  file:
    path: "{{ user_keychain_paths.ssh.src }}"
    state: directory
    mode: 0755
  tags:
    - config

- name: "user: Ensure state of keychain ssh destination folder"
  become: true
  file:
    path: "{{ user_keychain_paths.ssh.dest }}"
    owner: "{{ user_instance.user }}"
    group: "{{ user_instance.user }}"
    mode: 0755
    recurse: yes
    state: directory
  tags:
    - config

- name: "user: Ensure state of git repositories"
  become: true
  git:
    repo: "{{ user_git.src }}"
    version: "{{ user_git.version }}"
    clone: "{{ user_git.clone }}"
    dest: "{{ user_git.dest }}"
    force: "{{ user_git.force }}"
  loop: "{{ user_gits | default([]) }}"
  loop_control:
    loop_var: user_git
  tags:
    - install

- name: "user: Ensure state of keys in keychains for ssh"
  delegate_to: localhost
  run_once: true
  become: false
  shell:
    ssh-keygen -b 2048 -t rsa -f {{ user_keychain_files.ssh.private_key.src }} -N '' -C ''
  args:
    creates: "{{ user_keychain_files.ssh.private_key.src }}"
  tags:
    - config

- name: "user: Ensure state of authorized_keys"
  become: true
  authorized_key:
    user: "{{ user_instance.user }}"
    key: "{{ lookup('file', user_keychain_files.ssh.public_key.src) }}"
    state: present
  tags:
    - configure

- name: "user: Ensure state of ssh public keys"
  become: true
  copy:
    src: "{{ user_keychain_files.ssh.public_key.src }}"
    dest: "{{ user_keychain_files.ssh.public_key.dest }}"
    force: yes
    owner: "{{ user_instance.user }}"
    group: "{{ user_instance.user }}"
    mode: 0644
  tags:
    - configure

- name: "user: Ensure state of ssh private keys"
  become: true
  copy:
    src: "{{ user_keychain_files.ssh.private_key.src }}"
    dest: "{{ user_keychain_files.ssh.private_key.dest }}"
    force: yes
    owner: "{{ user_instance.user }}"
    group: "{{ user_instance.user }}"
    mode: 0600
  tags:
    - configure

- name: "user: Ensure state of permissions in homedir folder"
  become: true
  file:
    path: "{{ user_instance.homedir }}"
    owner: "{{ user_instance.user }}"
    group: "{{ user_instance.user }}"
    recurse: yes
    state: directory
  tags:
    - config
