---
- name: "virtualbox: Load variables"
  include_vars:
    file: "virtualbox.yml"

- name: "virtualbox: Ensure state of repository"
  when: virtualbox_repos|length > 0
  become: true
  yum_repository:
    name: "{{ virtualbox_repo.name }}"
    baseurl: "{{ virtualbox_repo.baseurl }}"
    description: "{{ virtualbox_repo.description | default(omit) }}"
    gpgcheck: "{{ virtualbox_repo.gpgcheck | default(omit) }}"
    enabled: "{{ virtualbox_repo.enabled | default(omit) }}"
    repo_gpgcheck: "{{ virtualbox_repo.repo_gpgcheck | default(omit) }}"
    gpgkey: "{{ virtualbox_repo.gpgkey | default(omit) }}"
  loop: "{{ virtualbox_repos }}"
  loop_control:
    loop_var: virtualbox_repo
  tags:
    - configure

- name: "virtualbox: Ensure state of packages"
  when: virtualbox_packages|length > 0
  become: true
  yum:
    name: "{{ virtualbox_package.name }}"
    state: "{{ virtualbox_package.state  | default(omit) }}"
    update_cache: "{{ virtualbox_package.update_cache | default(omit) }}"
  loop: "{{ virtualbox_packages }}"
  loop_control:
    loop_var: virtualbox_package
  tags:
    - install

- name: "libvirt: Ensure state of system group {{ virtualbox_auth.group }}"
  become: true
  group:
    name: "{{ virtualbox_auth.group }}"
    state: present
    system: yes
  tags:
    - configure

- name: "virtualbox: Ensure state of user as member of {{ virtualbox_auth.group }}"
  become: true
  user:
    name: "{{ ansible_user|default(lookup('env', 'USER'), True) }}"
    groups: "{{ virtualbox_auth.groups }}"
    append: yes
  tags:
    - configure
